### PR TITLE
ATTENTION HAMU

### PR DESCRIPTION
**Pull request by ThatOSDev**
HAMU, DELETE YOUR REPO AND USE MY OFFICIAL VERSION WHICH HAS ALL 30+ TUTS.
YOURS ONLY GOES UP TO 12.

### CODE REVIEW

**Comment by Marpuriganesh** [comment]
Buddy, can you please check your code in ThatOS repo where the code5 and code6 are no longer functional.....I left an issue in that repo ..... and one more thing thanks for making those tutorials both on youtube and on GitHub  it's really amazing that to find out even windows can be used for developing OS.....I am only saying that because I was able to find a way to contact you

**Comment by ThatOSDev** [comment]
Glad someone liked my videos and code. The guy who has my videos on his channel did so without my permission. Other then that, enjoy them. HOWEVER... I posted this message to HAMU to update his repo. He even stated in the readme that he would delete his version of the repo, and he can use mine. But I hadn't heard back from him yet. Even when I messaged him about this back in Feburary. Still no reply from this guy.

**Comment by ThatOSDev** [comment]
> Buddy, can you please check your code in ThatOS repo where the code5 and code6 are no longer functional.....I left an issue in that repo ..... and one more thing thanks for making those tutorials both on youtube and on GitHub it's really amazing that to find out even windows can be used for developing OS.....I am only saying that here because I was unable to find a way to contact you

If you need to get hold of me, my official email is uefidev@protonmail.com. The email and discord that is posted on that guys youtube channel doesn't reach me, they go to his accounts. He is pretending to be me.

**Comment by Marpuriganesh** [comment]
Thanks you buddy

**Pull request closed without merging**
